
const blueDeck=[
    
{question:"stirrup oak her",answer:"strip poker",hint:"naked games"},
{question:"bud dish hots",answer:"body shots",hint:"belly button"},
{question:"parr grr all",answer:"bar crawl",hint:"on to the next"},
{question:"mails drip her",answer:"male stripper",hint:"dollar bills"},
{question:"hug cup called sure",answer:"hookup culture",hint:"sleeping around"},
{question:"bod dull hope inner",answer:"bottle opener",hint:"cork"},
{question:"met tickle mayor won huh",answer:"medical marijuana",hint:"anxiety"},
{question:"half dare bar tee",answer:"after party",hint:"round 2"},
{question:"trunk cog holes",answer:"drunk goggles",hint:"tipsy eyes"},
{question:"way camp ache",answer:"wake and bake",hint:"off to a good start"},
{question:"pod pro niece",answer:"pot brownies",hint:"chill chocolate"},
{question:"diss sicken ate it rif e her",answer:"designated driver",hint:"the real MVP tonight"},
{question:"ford went he",answer:"4/20",hint:"national holiday"},
{question:"pup of as",answer:"puff puff pass",hint:"joint instructions"},
{question:"may get train",answer:"make it rain",hint:"good weather"},
{question:"past hutch owe ain't",answer:"pass the joint",hint:"split the pot"},
{question:"shod game ink appear",answer:"shotgunning a beer",hint:"quick drink"},
{question:"par dave owl",answer:"party foul",hint:"socially unacceptable"},
{question:"can ebb hiss",answer:"cannabis",hint:"like MJ"},
{question:"ha tub ox sing",answer:"hot boxing",hint:"foggy car"},
{question:"hid tub pong",answer:"hit the bong",hint:"bike toke"},
{question:"merry one nah",answer:"marijuana",hint:"lazy leaf"},
{question:"wad herb pong",answer:"water bong",hint:"purified smoke"},
{question:"read soul oak up",answer:"red solo cup",hint:"beer pong"},
{question:"jew wool bod",answer:"juulpod",hint:"new cigs"},
{question:"graph tub here",answer:"craft beer",hint:"not bud light"},
{question:"spend tub ought all",answer:"spin the bottle",hint:"kiss kiss"},
{question:"bought til cervix",answer:"bottle service",hint:"grey goose"},
{question:"due rug tess",answer:"drug test",hint:"pee cup"},
{question:"fizz dub hum bing",answer:"fist pumping",hint:"clubbing"},
{question:"moan cheese",answer:"munchies",hint:"hangry"},
{question:"tech heel huts hot",answer:"tequila shot",hint:"lots of lime"},
{question:"read bow fog caw",answer:"redbull vodka",hint:"classic combo"},
{question:"score be on pole",answer:"scorpion bowl",hint:"group drink"},
{question:"pod tum mull his minnows us",answer:"bottomless mimosas",hint:"brunch"},
{question:"hids fie folk logs hum aware",answer:"it’s 5 o’clock somewhere",hint:"time to drink"},
{question:"drub bet lie kits sot",answer:"drop it like it’s hot",hint:"snooooop"},
{question:"napper half fie heifer",answer:"never have i ever",hint:"secrets told"},
{question:"ball hack doubt",answer:"blacked out",hint:"drunken darkness"},
{question:"cram pear heave ought caw",answer:"cranberry vodka",hint:"spiked juice"},
{question:"tab pith hug egg",answer:"tap the egg",hint:"pour the beer"},
{question:"pinch shrink gang",answer:"binge drinking",hint:"dedicated hydration"},
{question:"barrel limp picks",answer:"beer olympics",hint:"local competition"},
{question:"furl oak hoe",answer:"four loko",hint:"banned substance"},
{question:"far tin gimp up lick",answer:"farting in public",hint:"noisy outside"},
{question:"bogs due i’m",answer:"boxed wine",hint:"franzia"},
{question:"hank oaf irk your",answer:"hangover cure",hint:"sunday medication"},
{question:"paw where our",answer:"power hour",hint:"beer timer"},
{question:"sog key pom",answer:"sake bomb",hint:"beer cocktail"},
{question:"jane’s moat king",answer:"chain-smoking",hint:"lotta butts"},
{question:"fay guy tee",answer:"fake ID",hint:"golden ticket"},
{question:"bob pin bought tolls",answer:"poppin’ bottles",hint:"champagne"},
{question:"app he yeah war",answer:"happy hour",hint:"joyous time"},
{question:"muzz comb you’ll",answer:"moscow mule",hint:"russian donkey"},
{question:"pain yuck hole odd huh",answer:"piña colada",hint:"pineapple punch"},
{question:"dirt rugged heel her",answer:"drug dealer",hint:"weed"},
{question:"thor tier hack",answer:"30 rack",hint:"bud light"},
{question:"saws itch barred hay",answer:"sausage party",hint:"all male"},
{question:"dare team art teenie",answer:"dirty martini",hint:"not clean"},
{question:"ease zig are wet",answer:"e-cigarette",hint:"juul"},
{question:"peer belle he",answer:"beer belly",hint:"too much bud"},
{question:"mark car eat duh",answer:"margarita",hint:"salty rim"},
{question:"room manned coat",answer:"rum and coke",hint:"classic combo"},
{question:"shale low shods",answer:"jello shots",hint:"dessert drink"},
{question:"prow nowed",answer:"brown out",hint:"one too many"},
{question:"raw link babe hair",answer:"rolling paper",hint:"green accessory"},
{question:"tea ages he",answer:"THC",hint:"hippie chemistry"},
{question:"kay gust ands",answer:"keg stands",hint:"tap it"},
{question:"foal hip cub",answer:"flip cup",hint:"red solo"},
{question:"hog tote bear vest",answer:"oktoberfest",hint:"bier"},
{question:"gin dairy feel barred tee",answer:"gender-reveal party",hint:"pink or blue"},
{question:"trunk eggs stink",answer:"drunk texting",hint:"idk where i am"},
{question:"seep peed he wile",answer:"CBD oil",hint:"for anxiety"},
{question:"past hutch owe ain’t",answer:"pass the joint",hint:"split the pot"},
{question:"shod gone ink appear",answer:"shotgunning a beer",hint:"quick drink"}
];
const yellowDeck=[


    {question:"fit he sheds off cray",answer:"fifty shades of grey",hint:"whips and chain"},
    {question:"fog chair he",answer:"fuckjerry",hint:"meme account"},
    {question:"guy leech hen her",answer:"kylie jenner",hint:"makeup"},
    {question:"trick her worn in",answer:"trigger warning",hint:"alert"},
    {question:"crap temp eye tub pushy",answer:"grab them by the pussy",hint:"trump advice"},
    {question:"nun she ammo",answer:"non-GMO",hint:"nutrition"},
    {question:"hatch meows hide hobo dad",answer:"cash me ousside how bow dat",hint:"dr. phil"},
    {question:"fish hits bin hers",answer:"fidget spinners",hint:"rotating distraction"},
    {question:"hue own lee leaf ones",answer:"you only live once",hint:"limited existence"},
    {question:"day yam tan knee hole",answer:"damn daniel",hint:"white vans"},
    {question:"knit flick sand shill",answer:"netflix and chill",hint:"watching movies"},
    {question:"sad hurt ace surf forth a voice",answer:"saturdays are for the boys",hint:"barstool sports"},
    {question:"thatch hutches lied",answer:"the cha cha slide",hint:"wedding moves"},
    {question:"their heels limp shed he",answer:"the real slim shady",hint:"eminem"},
    {question:"sid hop drying tomb ache kvetch have been",answer:"stop trying to make fetch happen",hint:"regina george"},
    {question:"own wind stays weave hair ping",answer:"on wednesdays, we wear pink",hint:"weekly color preference"},
    {question:"hid sprint heap itch",answer:"it’s britney bitch!",hint:"oops!... i did it again"},
    {question:"veer off mess sing oat",answer:"fear of missing out",hint:"social anxiety"},
    {question:"this drug gull israel",answer:"the struggle is real",hint:"first world problems"},
    {question:"hint turn ed rolls",answer:"internet trolls",hint:"online bullies"},
    {question:"real agents sip gulls",answer:"relationship goals",hint:"power couple"},
    {question:"hike ant eve hen",answer:"i can’t even",hint:"ugh, whatever"},
    {question:"per rake tee inner ned",answer:"break the internet",hint:"crash the web"},
    {question:"boy full leash awe",answer:"bye, felicia",hint:"adios, amiga"},
    {question:"hey dares con a hayed",answer:"haters gonna hate",hint:"critics criticize"},
    {question:"hay knob putty god dime fourth hat",answer:"ain’t nobody got time for that",hint:"i got bronchitis"},
    {question:"tad swat cheese head",answer:"that’s what she said",hint:"classic response"},
    {question:"razzled ding pitch vase",answer:"resting bitch face",hint:"lingering facial rage"},
    {question:"plaid for men eye nan tree quoters",answer:"platform 9 3/4",hint:"brick column"},
    {question:"fifed holler food lawn",answer:"5-dollar footlong",hint:"eat fresh"},
    {question:"pig bull",answer:"big baller brand",hint:"lonzo"},
    {question:"hints tug rams hole leper hid tea",answer:"instagram celebrity",hint:"internet famous"},
    {question:"dez pus seed hoe",answer:"despacito",hint:"taquito, dorito"},
    {question:"ham a sauna let’s uh",answer:"amazon alexa",hint:"robot commands"},
    {question:"stir range earth inks",answer:"stranger things",hint:"upside down"},
    {question:"came off drones",answer:"game of thrones",hint:"iron throne"},
    {question:"brute teen pout her",answer:"protein powder",hint:"strong sugar"},
    {question:"sun nap chad’s door he",answer:"snapchat story",hint:"24-hour special"},
    {question:"hints toe cram starry",answer:"instagram story",hint:"no filter"},
    {question:"hud yolk uh",answer:"hot yoga",hint:"warm stretching"},
    {question:"hoop purr pull",answer:"uber pool",hint:"shared ride"},
    {question:"tethers diss rail",answer:"the thirst is real",hint:"parched"},
    {question:"bull lag fried hay",answer:"black friday",hint:"crazy shopping"},
    {question:"aight hook uphill henna bees uh",answer:"i took a pill in ibiza",hint:"mike posner"},
    {question:"sure gore furry",answer:"sugar-free",hint:"boring alternative"},
    {question:"glide much henge",answer:"climate change",hint:"carbon crisis"},
    {question:"cause mob hole lid in",answer:"cosmopolitan",hint:"drink and mag"},
    {question:"king cord ash yen whizzed",answer:"kim kardashian west",hint:"keeping up"},
    {question:"mic cup two door real",answer:"makeup tutorial",hint:"beauty 101"},
    {question:"tint hurt eight",answer:"tinder date",hint:"it’s a match"},
    {question:"purr roam hands",answer:"bromance",hint:"i love you, man"},
    {question:"bell who awful",answer:"bue waffle",hint:"fake STD"},
    {question:"wear caw haul leg",answer:"workaholic",hint:"job addicted"},
    {question:"freak when doff liar my holes",answer:"frequent flyer miles",hint:"united airlines"},
    {question:"huh verb oar duh",answer:"hoverboard",hint:"scooter"},
    {question:"prix aunt kush hoe bra",answer:"priyanka chopra",hint:"bollywood"},
    {question:"sate donut spur aid hit",answer:"sait it, don’t spray it",hint:"saliva"},
    {question:"glow eek hard ashy am",answer:"khloe kardashian",hint:"keeping up"},
    {question:"vector hero yell",answer:"victory royale",hint:"fortnite"},
    {question:"ton hold romp shoe near",answer:"donald trump jr.",hint:"son of a"},
    {question:"mime elks ache brim saul dubai’s tooth uh yod",answer:"my milkshake brings all the boys to the yard",hint:"booty shake"},
    {question:"huge act mend",answer:"hugh jackman",hint:"wolverine"},
    {question:"why and ran holds",answer:"ryan reynolds",hint:"actor"},
    {question:"bay beam on uh",answer:"baby mama",hint:"parent"},
    {question:"debt tub bool",answer:"deadpool",hint:"superhero"},
    {question:"tech a gel pal",answer:"take a chill pill",hint:"overreacting"},
    {question:"star mead annuals",answer:"stormy daniels",hint:"bad weather"},
    {question:"foot comb uh",answer:"food coma",hint:"thanksgiving"},
    {question:"fenced a hug hound",answer:"finsta account",hint:"second profile"},
    {question:"tech get mads tear",answer:"ticketmaster",hint:"event boss"},
    {question:"yeah skew ween",answer:"yasss queen",hint:"you go girl"},
    {question:"knew foam hood is",answer:"new phone, who dis?",hint:"no contacts"},
    {question:"croupe miss itch",answer:"group message",hint:"text us"},
    {question:"furry wife eye",answer:"free wifi",hint:"starbucks"},
    {question:"stuff fin cure ray",answer:"stephen curry",hint:"MVP"},
    {question:"iowa cope lie hiss",answer:"i woke up like this",hint:"flawless"},
    {question:"soak wad coals",answer:"squad coals",hint:"cool kids"},
    {question:"gash shole knee",answer:"cash only",hint:"ATM"},
    {question:"for tea your all diversion",answer:"40 year old virgin",hint:"steve carell"},
    {question:"had meow null ink den",answer:"add me on linkedin",hint:"networking"},
    {question:"jews cull lens",answer:"juice cleanse",hint:"liquid health"},
    {question:"of venture sin fin it you oar",answer:"avengers: infinite war",hint:"thanos"},
    {question:"whole avant form wrist mist issue",answer:"all i want for christmas is you",hint:"mariah"},
    {question:"furry dude aid chip ping",answer:"free 2-day shipping",hint:"prime target"},
    {question:"hue nick horn fir rap bush sheen owe",answer:"unicorn frappuccino",hint:"magical drink"},
    {question:"broke he monk hoe",answer:"pokemon go",hint:"pikachu"},
    {question:"stir hate owe dug humped in",answer:"straight outta compton",hint:"ice cube"},
    {question:"clue tin furry",answer:"gluten-free",hint:"fake bread"},
    {question:"died botch ill hinge",answer:"tide pod challenge",hint:"eating soap"},
    {question:"mocks suck curb berk",answer:"mark zuckerberg",hint:"news feed"},
    {question:"sue why bride",answer:"swipe right",hint:"it’s a match"},
    {question:"set ton owe won heifer",answer:"said no one ever",hint:"snarky reply"},
    {question:"key bit won hunt rid",answer:"keep it 100",hint:"the real deal"},
    {question:"pitch pull ease",answer:"bitch please!",hint:"finger snap"},
    {question:"tour king",answer:"twerking",hint:"modern shake"},
    {question:"aim his own burr rhyme",answer:"amazon prime",hint:"bezos"},
    {question:"walk hun dove oar ev her",answer:"wakanda forever",hint:"east africa"},
    {question:"fur stew hurled prop plums",answer:"first world problems",hint:"not real issues"},
    {question:"comp hooch ya",answer:"kombucha",hint:"drink fad"},
    {question:"birch who’ll ray yell lid he",answer:"virtual reality",hint:"fake life"},
    {question:"sun nab shat filled her",answer:"snapchat filter",hint:"virtual makeup"},
    {question:"van heap hack",answer:"fanny pack",hint:"strap-on fashion"},
    {question:"bore dare well",answer:"border wall",hint:"trump’s fence"},
    {question:"shelf dry fink curse",answer:"self-driving cars",hint:"robo wheels"},
    {question:"that he itch use",answer:"daddy issues",hint:"father probs"},
    {question:"ran shore blush ease",answer:"ranch or blue cheese?",hint:"buffalo wings"},
    {question:"two huey fen lived pro",answer:"do you even lift, bro?",hint:"gym membership"},
    {question:"quack his sex draw",answer:"guac is extra",hint:"chipotle"},
    {question:"mayan knock honda toned",answer:"my anaconda don’t",hint:"nicki"},
    {question:"aims heck see hand eye note",answer:"i’m sexy and i know it",hint:"hot and confident"},
    {question:"burn niece handlers",answer:"bernie sanders",hint:"universal healthcare"},
    {question:"pressed feet tin",answer:"breastfeeding",hint:"milk"},
    {question:"yen if hearse sale elf kay her",answer:"universal healthcare",hint:"total support"},
    {question:"crib took her rinse see",answer:"cryptocurrency",hint:"fake moola"},
    {question:"boo pay moat she",answer:"poop emoji",hint:"smelly smile"},
    {question:"slight tint huey ore tea hems",answer:"slide into your DMs",hint:"pickup line"},
    {question:"vague noose",answer:"fake news",hint:"legit info"},
    {question:"ellen mayo",answer:"lmao",hint:"cracking up"},
    {question:"foe dope bum",answer:"photobomb",hint:"exploding image"},
    {question:"call ick bayed",answer:"clickbait",hint:"headliner"},
    {question:"womb hank rush when stay",answer:"women crush wednesday",hint:"hump day"},
    {question:"mank rush moaned hay",answer:"man crush monday",hint:"weekly bf post"},
    {question:"go shell law",answer:"coachella",hint:"getting festive"},
    {question:"pars duels boards",answer:"barstool sports",hint:"boston blog"},
    {question:"huff fog autoed host",answer:"avocado toast",hint:"best breakfast"},
    {question:"check hen nan due awfuls",answer:"chicken and waffles",hint:"soul food"},
    {question:"bump ken spies slot day",answer:"pumpkin spice latte",hint:"basic caffeine"},
    {question:"hids nod hue wets may",answer:"it’s not you, it’s me",hint:"breakup"},
    {question:"thorough winks aid",answer:"throwing shade",hint:"tossing insults"},
    {question:"bush rop raw",answer:"push up bra",hint:" lifted"},
    {question:"mere ores elf fee",answer:"mirror selfie",hint:"reflection"},
    {question:"sore hay nods ore hee",answer:"sorry not sorry",hint:"no apology"},
    {question:"buffers toll led meat ache us elf fee",answer:"but first let me take a selfie",hint:"wait snap a pic"},
    {question:"whirls tar rip pop",answer:"worldstar hiphop",hint:"fight videos"},
    {question:"bays sig up hitch",answer:"basic bitch",hint:"standard human"},
    {question:"duke earls swung up",answer:"two girls one cup",hint:"shit you can’t unsee"},
    {question:"beep perve favor",answer:"bieber fever",hint:"canadian sickness"},
    {question:"cough inks ease in",answer:"cuffing season",hint:"wintertime"},
    {question:"shake fur rum stayed of harm",answer:"jake from state farm",hint:"khaki model"},
    {question:"a dull thing",answer:"adulting",hint:"grown-up"},
    {question:"car mush up itch",answer:"karma’s a bitch",hint:"cause and effect"},
    {question:"starred if rum tub pot hum",answer:"started from the bottom",hint:"no privilege"},
    {question:"stalk hint of rends own",answer:"stuck in the friend zone",hint:"high five!"},
    {question:"thor dwee link",answer:"third wheeling",hint:"here for support"},
    {question:"dean mage purr wreck nun see",answer:"teenage pregnancy",hint:"young momma"},
    {question:"fun dizzy food pall",answer:"fantasy football",hint:"gambling"},
    {question:"pow hurk up pull",answer:"power couple",hint:"perfect pair"},
    {question:"sups cur ripe tomb eye sham null",answer:"subscribe to my channel",hint:"youtube"},
    {question:"jenner agency",answer:"generation z",hint:"up-and-coming"},
    {question:"cape gall manned care ray han",answer:"keep calm and carry on",hint:"poster"},
    {question:"fret shim in fit teen",answer:"freshman fifteen",hint:"collegiate perks"},
    {question:"ma shawl hot hey",answer:"matcha latte",hint:"new drink fad"},
    {question:"purry war cowed",answer:"pre workout",hint:"before lifting"},
    {question:"cell fees tick",answer:"selfie stick",hint:"photo assistant"},
    {question:"egg straw hay elf",answer:"extra af",hint:"so additional"},
    {question:"enter net vain muss",answer:"internet famous",hint:"known online"},
    {question:"sums how’d gums shout",answer:"sun’s out guns out",hint:"tank top"},
    {question:"shy hold dish camp he no",answer:"childish gambino",hint:"rapper"},
    {question:"ump hate hint urn zip",answer:"unpaid internship",hint:"college student"},
    {question:"the row pack thirst hay",answer:"throwback thursday",hint:"weekly memz"},
    {question:"cape in cup width hug hard ashy ins",answer:"keeping up with the kardashians",hint:"guilty pleasure"},
    {question:"wet thing seize hen",answer:"wedding season",hint:"promising series"},
    {question:"ike hot if rum mime hum uh",answer:"i got it from my momma",hint:"in my DNA"},
    {question:"odd doe core egged",answer:"autocorrect",hint:"text replacement"},
    {question:"bin joe wad shin",answer:"binge watching",hint:"tv marathon"},
    {question:"lung air toned gayer",answer:"long hair don’t care",hint:"lovely locks"},
    {question:"can mold oh",answer:"camel toe",hint:"sahara foot"},
    {question:"sill lab hiss wake",answer:"syllabus week",hint:"new semester"},
    {question:"ron men newt holes",answer:"ramen noodles",hint:"american delicacy"},
    {question:"fife oak log chad hoe",answer:"five o’clock shadow",hint:"short stubble"},
    {question:"pie juan kit won furry",answer:"buy 1 get 1 free",hint:"gmail promotion"},
    {question:"dime sinew roam men",answer:"times new roman",hint:"MLA format"},
    {question:"moor nim bur wrath",answer:"morning breath",hint:"wake-up smell"},
    {question:"snap bowl fax",answer:"snapple facts",hint:"liquid knowledge"},
    {question:"chest who wit",answer:"just do it",hint:"global slogan"},
    {question:"her pinned ick shun hairy",answer:"urban dictionary",hint:"fun meanings"},
    {question:"food cub hitches skit moan hay",answer:"fuck bitches get money",hint:"ignorant motto"},
    {question:"race sore perm",answer:"razor burn",hint:"shaving sucks"},
    {question:"hid scum plug hated",answer:"it’s complicated",hint:"relationship status"},
    {question:"lib full half all of",answer:"live laugh love",hint:"another poster quote"},
    {question:"dome hutch chin firm hey shun",answer:"too much information",hint:"but why"},
    {question:"a dent chum hoe were",answer:"attention whore",hint:"fame obsessed"},
    {question:"hope in real asian ship",answer:"open relationship",hint:"extramarital"},
    {question:"carp pull carry oak he",answer:"carpool karaoke",hint:"sing-along"},
    {question:"heir being bee",answer:"airbnb",hint:"couch surfing"},
    {question:"wind her ritz cum ink",answer:"winter is coming",hint:"snow"},
    {question:"tub hatch chill or wet",answer:"the bachelorette",hint:"love olympics"},
    {question:"kin trick loam are",answer:"kendrick lamar",hint:"DAMN."},
    {question:"shams there ab her",answer:"chance the rapper",hint:"probability"},
    {question:"neck key men notch",answer:"nicki minaj",hint:"anaconda"},
    {question:"cart he pea",answer:"cardi b",hint:"okurrrr"},
    {question:"gone yay whizzed",answer:"kanye west",hint:"genius"},
    {question:"dutch aims mole curse",answer:"the chainsmokers",hint:"cigarettes"},
    {question:"duh hammed mate stale",answer:"the handmaid’s tale",hint:"hulu"},
    {question:"if hung cut romp",answer:"ivanka trump",hint:"#1 daughter"},
    {question:"he’ll lawn mosque",answer:"elon musk",hint:"iron man"},
    {question:"hum pull bore rag",answer:"humblebrag",hint:"sneaky ego"},
    {question:"phase bucks tall king",answer:"facebook stalking",hint:"social spy"},
    {question:"trains form agent who’s stay",answer:"transformation tuesday",hint:"insta ritual"},
    {question:"ham ions peak her",answer:"am i on speaker",hint:"loud phone"},
    {question:"wads thaw why vibe ass sword",answer:"what’s the wifi password",hint:"saving data"},
    {question:"bay purse draws",answer:"paper straws",hint:"eco-friendly"},
    {question:"whip stone dull hi",answer:"hips don’t lie",hint:"shakira"},
    {question:"leak cull eyes mayor one huh",answer:"legalize marijuana",hint:"yes, mary"},
    {question:"low roll or yam knee",answer:"laurel or yanny",hint:"listen close"},
    {question:"son dane knived vote bowl",answer:"sunday night football",hint:"wings and pizza"},
    {question:"sit orange his alm oats fool",answer:"storage is almost full",hint:"need memory"},
    {question:"reed seating air lime",answer:"receding hairline",hint:"growing forehead"},
    {question:"cub hulls mesh hutch",answer:"couple’s massage",hint:"all the feels"},
    {question:"burr thick hunt roll",answer:"birth control",hint:"sexual safety"},
    {question:"red ray seeds",answer:"read receipts",hint:"imessage"},
    {question:"yolk hub ants",answer:"yoga pants",hint:"tight and comfy"},
    {question:"are he amuck ran day",answer:"ariana grande",hint:"ponytail"},
    {question:"shone ham knit tee",answer:"sean hannity",hint:"foxy"},
    {question:"men him hum owe age",answer:"minimum wage",hint:"per hour"},
    {question:"hoop heard rife fair",answer:"uber driver",hint:"5 stars"},
    {question:"pray kink how’d",answer:"breaking out",hint:"puberty"},
    {question:"eel lips sob bath wear in",answer:"elizabeth warren",hint:"native american"},
    {question:"gunk on troll",answer:"gun control",hint:"amendment"},
    {question:"grips seat high kin",answer:"chrissy teigen",hint:"legend"},
    {question:"brick gnat seed hest",answer:"pregnancy test",hint:"plus or minus"},
    {question:"eggs plows if dire hey ya",answer:"explosive diarrhea",hint:"boom toilet"},
    {question:"eggs pox sole i’ve",answer:"xbox live",hint:"video game"},
    {question:"fork hop as whirred",answer:"forgot password",hint:"username"},
    {question:"bore he’d dope pole",answer:"burrito bowl",hint:"chipotle"},
    {question:"ink hog knead ode",answer:"incognito mode",hint:"secret search"},
    {question:"far rat turn it heap rod her",answer:"fraternity brother",hint:"greekish"},
    {question:"full hi yank sole low",answer:"flying solo",hint:"free like a bird"},
    {question:"hen newest fill led dale fear porn hand raced",answer:"in west philadelphia born and raised",hint:"bel air"},
    {question:"stood den dead",answer:"student debt",hint:"so college"},
    {question:"calf itched",answer:"catfished",hint:"fake ID"},
    {question:"meh come air ick auger rate akin",answer:"make american great again",hint:"on a red hat"},
    {question:"hill loom men hottie",answer:"illuminati",hint:"beyonce"},
    {question:"shin me fail on",answer:"jimmy fallon",hint:"late night"},
    {question:"awed toad dune",answer:"autotune",hint:"t-pain"},
    {question:"lint seal owe hand",answer:"lindsay lohan",hint:"parent trap"},
    {question:"lug would chew mate made who",answer:"look what you made me do",hint:"swift"},
    {question:"brr had leak hoop her",answer:"bradley cooper",hint:"a star is born"},
    {question:"torn town furrow hut",answer:"turn down for what",hint:"lil jon"},
    {question:"hone limed agree",answer:"online degree",hint:"phoenix"},
    {question:"fifes heck gunned roll",answer:"five second rule",hint:"safe to eat"},
    {question:"check full hay",answer:"chick fil a",hint:"christian food"},
    {question:"coal ledge job how’d",answer:"college dropout",hint:"zuckerberg"},
    {question:"bus so feat",answer:"buzzfeed",hint:"online quiz"},
    {question:"eighty age tee",answer:"adhd",hint:"can’t sit still"},
    {question:"we’re duh flax bud oak hay",answer:"weird flex but ok",hint:"show off"},
    {question:"beer purr retch her",answer:"peer pressure",hint:"c’mon, do it"},
    {question:"fair if i’d hook hound",answer:"verified account",hint:"blue check mark"},
    {question:"hints stuck ramp gap shin",answer:"instagram caption",hint:"subtitle"},
    {question:"son herb pod",answer:"summer bod",hint:"six pack"},
    {question:"phase poke off his shoal",answer:"facebook official",hint:"in a relationship"},
    {question:"burrows pea four rose",answer:"bros before hoes",hint:"fratty motto"},
    {question:"coal brook off he",answer:"cold brew coffee",hint:"icy caffeine"},
    {question:"pig sore hit tint tap open",answer:"pics or it didn’t happen",hint:"picture proof"},
    {question:"haze sear ray",answer:"hey siri",hint:"personal assistant"},
    {question:"pole lid tick glee anchor wrecked",answer:"politically incorrect",hint:"offensive"},
    {question:"hall moan dumb elk",answer:"almond milk",hint:"nutty drink"},
    {question:"shoals hike hole",answer:"soulcycle",hint:"bike club"},
    {question:"heart fish hole and hell itch hens",answer:"artificial intelligence",hint:"fake smart"},
    {question:"herb pam how’d tvet hers",answer:"urban outfitters",hint:"cool clothes"},
    {question:"ab pole moose sick",answer:"apple music",hint:"fruit tunes"},
    {question:"shone meant diss",answer:"shawn mendes",hint:"in my blood"},
    {question:"pose dumb alone",answer:"post malone",hint:"face tats"},
    {question:"meat whom hoove mint",answer:"me too movement",hint:"time’s up"},
    {question:"sack jewel lorry hen day chin",answer:"sexual orientation",hint:"born this way"},
    {question:"hay thee yes sim",answer:"atheism",hint:"ungodly"},
    {question:"pot turn knit teed hest",answer:"paternity test",hint:"maury"},
    {question:"rush a knack king",answer:"russian hacking",hint:"interference"},
    {question:"fray dome muffs beach",answer:"freedom of speech",hint:"say whatcha want"},
    {question:"sigh burp pully inn",answer:"cyberbullying",hint:"virtual villain"},
    {question:"ache quill bay",answer:"equal pay",hint:"every dollar counts"},
    {question:"calf finned her ant",answer:"kevin durant",hint:"top baller"},
    {question:"low camp haul",answer:"logan paul",hint:"social media star"},
    {question:"press hid hinder ump",answer:"president trump",hint:"orange face"},
    {question:"jim tam lawn tree",answer:"gym tan laundry",hint:"jersey shore"},
    {question:"rope herd mule lore",answer:"robert mueller",hint:"special detective"},
    {question:"kin chaw noon",answer:"kim jong un",hint:"rocket man"},
    {question:"kin you’ve hem mow mi",answer:"can you venmo me",hint:"split the bill"},
    {question:"vie her vest if all",answer:"fyre festival",hint:"fake event"},
    {question:"snake her reds",answer:"sneakerheads",hint:"new shoes"},
    {question:"him pea chum mint",answer:"impeachment",hint:"mueller"},
    

]

module.exports={blueDeck,yellowDeck};